# Generated by Django 5.1.7 on 2025-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Escritório e Papelaria', 'Escritório e Papelaria'), ('Eletrônicos', 'Eletrônicos'), ('Alimentos', 'Alimentos')], max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
